#logging:
#  level:
#    org.springframework.security: TRACE
#    org.hibernate: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.orm.jpa: DEBUG
#
#
